
export interface User {
    id: string;
    email: string;
    password: string;

}

interface HabitFields {
    id?: string;         // Auto-generated by Prisma
    title: string;
    description?: string | null;
    frequency: string;
    startDate: Date;
    userId: string;      // Never allowed to update
    archived?: boolean;  // Only for updates
    createdAt?: Date;    // Auto-generated
    updatedAt?: Date;    // Auto-updated
}



export type HabitCreateInput = Pick<HabitFields, "title" | "frequency" | "startDate" | "userId"> & {
    description?: string | null;
}

export type HabitUpdateInput = Partial<Pick<HabitFields, "title" | "frequency" | "description">>;
export interface HabitInput {
    title: string;
    description?: string | null;
    frequency: string;
    startDate: Date;
    userId: string;
}